package com.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Id")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Address")
	private com.poc.Address address;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Person [name=" + name + ", id=" + id + ", address=" + address
				+ "]";
	}

	public com.poc.Address getAddress() {
		return this.address;
	}

	public void setAddress(com.poc.Address address) {
		this.address = address;
	}

	public Person(java.lang.String name, java.lang.Long id,
			com.poc.Address address) {
		this.name = name;
		this.id = id;
		this.address = address;
	}

}